# Generated by Django 5.2.1 on 2025-07-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_detailpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailPage',
            new_name='ProductPage',
        ),
    ]
