# Generated by Django 5.2.1 on 2025-07-15 09:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_detailpage_productpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=234, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpage',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
