# Generated by Django 5.2.1 on 2025-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_productpage_delete_detailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('squared', 'Squared'), ('other', 'Other')], default='horizontal', max_length=10),
        ),
    ]
