# Generated by Django 5.2.1 on 2025-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_productpage_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description_text',
            field=models.TextField(blank=True, help_text='Einfacher Text für eine zusätzliche Beschreibung.'),
        ),
    ]
