# Generated by Django 5.2.1 on 2025-11-05 21:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_productpage_description_text'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='shoppage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videographypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='description',
        ),
        migrations.AddField(
            model_name='photographypage',
            name='intro_subtitle',
            field=models.TextField(blank=True, help_text='The first line of body text (larger font)'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='The second line of body text (smaller font)'),
        ),
        migrations.AddField(
            model_name='photographypage',
            name='intro_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PhotographyPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.photographypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='FaqPage',
        ),
        migrations.DeleteModel(
            name='ShopPage',
        ),
        migrations.DeleteModel(
            name='VideographyPage',
        ),
    ]
