# Generated by Django 5.2.1 on 2025-11-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_blogpage_page_ptr_remove_contactpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_subtitle',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='photographypage',
            name='intro_title',
        ),
        migrations.DeleteModel(
            name='PhotographyPageGalleryImage',
        ),
    ]
